### ISSUE TITLE
root access does not pop up

### ISSUE THREAD

**Issue by Caelestrasz** [jacopotediosi/GAppsMod#107]
I have rooted my phone，but the app cannot access root permission

oneplus oxygen 13.1
magisk 26.3

![Screenshot_20231001140608.jpg](https://github.com/jacopotediosi/GAppsMod/assets/25895906/76fbc16c-1e7e-4c4f-9e53-15cc2e6261ad)

![Screenshot_20231001140428.jpg](https://github.com/jacopotediosi/GAppsMod/assets/25895906/74da3c7c-b230-49b3-98f3-ae685dadc611)

![Screenshot_20231001140554.jpg](https://github.com/jacopotediosi/GAppsMod/assets/25895906/eda04a99-8eb9-4a43-b9a9-d5392dc7e4c0)

![Screenshot_20231001140530.jpg](https://github.com/jacopotediosi/GAppsMod/assets/25895906/2d52b7ae-69db-44f1-9b7d-6d6fc118bd58)

**Comment by jacopotediosi** [comment]
Just go to the "Root Access" Magisk tab and allow root access to GAppsMod.

**Comment by Caelestrasz** [comment]
gappsmod is not on "Root Access" Magisk tab. so I can't find anywhere to give root permisssion.

**Comment by jacopotediosi** [comment]
GAppsMod uses Libsu to manage root, which is created by the same developer as Magisk. In particular, the code to request shell access is copy-pasted from the documentation. Are you sure your Magisk setup is working? Do other rooted applications work correctly?

**Comment by Caelestrasz** [comment]
Yes，the other rooted applications work correctly.
![Screenshot_20231005154301.jpg](https://github.com/jacopotediosi/GAppsMod/assets/25895906/298c3de8-8de3-4885-918c-518152517bb9)

**Comment by jacopotediosi** [comment]
Those in your screenshot are Magisk modules, not root applications.

**Comment by jacopotediosi** [comment]
Root Access is the second tab from left

**Comment by Caelestrasz** [comment]
![Screenshot_2023-10-05-16-28-00-91.jpg](https://github.com/jacopotediosi/GAppsMod/assets/25895906/42f027f4-7f44-4f7e-816a-2566aee1e37e)
