### ISSUE TITLE
Silence call recording alerts for all dialer versions

### ISSUE THREAD

**Issue by cygiel5420** [jacopotediosi/GAppsMod#112]
## Summary
[NOTE]: # ( Provide a brief overview of what the new feature is all about )
Enable silencing the phone recording announcement on all versions of Google Dialer, not just <=94 

## Solution
[NOTE]: # ( A clear and concise description of what you want to happen )
Be able to toggle "silence phone recording alerts" on newer versions of Google Dialer App, similar to how Pixel Xpert mod can do.

## Examples
[NOTE]: # ( Show us a picture or mock-up of your proposal )
Not sure, haven't looked at the GAppsMod code, but Pixel Xpert sends a "null" value for "recording message" variable.
[Link to their Dialer code](https://github.com/siavash79/PixelXpert/blob/canary/app/src/main/java/sh/siava/pixelxpert/modpacks/dialer/RecordingMessage.java)

## Alternatives
[NOTE]: # ( A clear and concise description of any alternative solutions or features you've considered )
No alternatives.

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )
Don't want to be installing TTSLexx and manually changing TTS output just to silence those alerts. 1 in all solution would be a nice to have. Also, Pixel Xpert doesn't want to install properly on A14 CrDroid ROM with Kitsune Mask and LSPosed, and GAppsMod work just fine.

**Comment by jacopotediosi** [comment]
Again (you didn't read other issues), GAppsMod can't change Dialer source codes, varaibles etc. This is not an LSPosed module. This is just an editor for the Google Play Services Phenotype DB. This issue is out of scope for this project.
