### ISSUE TITLE
Call Recording and Call Screen disabled

### ISSUE THREAD

**Issue by scarlion1** [jacopotediosi/GAppsMod#114]
Sorry I don't have time to fill this out completely, will update it fully ASAP but wanted to get this report started in case there might be an apparent fix ahead of time.

## Overview
[NOTE]: # ( Give a BRIEF summary about your problem )
Google is up to malicious interference again and has crossed some serious lines with recent Phone updates and disabled my call recording and screening.  It seems Phone was updated on Jan 11 to version 121.0.596421684-publicbeta.  Several days ago I got a permanent notification shown from Phone that "**Always record is off**" and "The feature is not available in your location.  Calls from unknown and selected numbers won't be recorded."  Upon opening the Phone settings, there's a bright red banner that had some nonsensical big brother intrusion into my private affairs, explaining they know better than I do...  Even if they did, it's not their job to enforce the laws they think exist anyway.  The recording switches were in off position and disabled from moving.  

Upon re-opening GAppsMod, Recording and Screening are both off.  After turning those back on and force-closing and re-opening Phone several times, the notification and banner have both disappeared and a test call with recording turned on was successful.

However, Call Screen is only partially working.  It used to be fine, but now when the initial screen is opened, I'm pretty sure those google dots on the left were colored before, indicating it was "ON".
![image](https://github.com/jacopotediosi/GAppsMod/assets/2446600/5cbbd717-d3af-4402-bb73-cc92cad63e02)

Also when I tap on that for more settings, it was saying "Activating Call Screen (requires WiFi)" for several days.  Now that disappears.  The first two items under "Unknown Call Settings" (Spam, Possibly faked numbers) appear to be on with colors dots while last two settings (First Time Callers, and Private & Hidden Numbers) don't have colored dots.  If I tap on any of the options, the app crashes and asks me to reopen it, which I've done many times, also tried clearing the cache.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1.  I guess, use a Phone version prior to 121.0.596421684-publicbeta
2.  Installed GAppsMod and enabled screening and recording, tested to be working fine.
3.  Upgrade Phone to 121.0.596421684-publicbeta

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Call screening and recording continue to work.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
Call screening and recording are disabled, with un-clearable notification and red banner in Phone for days

## Screenshots
[NOTE]: # ( If applicable, add screenshots to help explain your problem. )
N/A

## System Information
- Device and model: Pixel 5a

- ROM and Android version: 11

- Is the Google app you are trying to tweak (e.g., Phone by Google) installed as system app: yes

- Installed Magisk / other SU Manager version: Magisk 26.1

[NOTE]: # ( Paste below the output of the `adb shell "dumpsys package com.jacopomii.gappsmod | grep version"` command )
**- Installed GAppsMod version:**

[NOTE]: # ( Paste below the output of the `adb shell "dumpsys package REPLACE_WITH_PACKAGENAME | grep version"` command )
**- The version of the Google app you are trying to tweak (e.g., Phone by Google): Phone by Google 121.0.596421684-publicbeta?**

[NOTE]: # ( Paste below the output of the `adb shell "getprop | grep locale"` command )
**- Your device language (locale): en?**

[NOTE]: # ( Paste below the output of the `adb shell "getprop | grep iso-country"` command )
**- Your location (country of the SIM and country where you are): USA**

## Logcat
[NOTE]: # ( Launch the Google app you are trying to tweak (e.g., Phone by Google) in Debug mode using the `adb shell "am start -D REPLACE_WITH_PACKAGENAME"` command.
Open another terminal and use the `adb logcat > logs.txt` command to start capturing logs.
Perform the necessary steps to replicate the bug, then press CTRL+C to stop capturing logs.
Attach below the resulting logs.txt file. )

**TBA**

**Comment by jacopotediosi** [comment]
- Regarding the sudden disabling of flags: probably Phone by Google or some other Google app corrupted the Phenotype DB. It can happen sometimes. I recommend that you delete the data from the Google Play Services and Phone by Google apps and try to enable the features again with GAppsMod.
- Regarding the crash of the Call Screen options: I confirm that the latest beta of the Phone by Google crashes. But this does not depend on GAppsMod and it's happening also to Pixel users without mods. After all, it's called Beta for a reason.

**Comment by scarlion1** [comment]
Thanks, when you recommend "delete the data" you mean "cache" or "storage" data, or both?  I don't really like clearing the "storage" data (in Phone at least) since that probably has my call log and history + recordings, doesn't it?  Can that be backed up/restored?  Maybe as a last resort...

Thanks for finding out other Pixel users also having problems with Call Screen.  I was under the impression we needed beta versions of apps in order for GAppsMod to work?  Maybe that was a long time ago...  is it not the case then, and I can opt out of the Phone beta?

**Comment by jacopotediosi** [comment]
> when you recommend "delete the data" you mean "cache" or "storage" data, or both?  I don't really like clearing the "storage" data (in Phone at least) since that probably has my call log and history + recordings, doesn't it?

The call log and history are stored by Android, not in the dialer app's data folder, because they must also be available to any other dialer application installed on your phone, not just Phone by Google. However, deleting Phone by Google data will delete the phone call recordings.

It is instead absolutely safe to delete the Google Play Services data, so that the corrupted phenotype db will be recreated.
 
> Thanks for finding out other Pixel users also having problems with Call Screen.  I was under the impression we needed beta versions of apps in order for GAppsMod to work?  Maybe that was a long time ago...  is it not the case then, and I can opt out of the Phone beta?

Some hidden features requires beta, but the Suggested Mods of GAppsMod now also work on stable versions of Google apps, as they were implemented long time ago.

**Comment by scarlion1** [comment]
Awesome, thanks for the explanation.  So, I opted out of the Google Phone beta but it kept reinstalling the beta version until I rebooted, now I've got version 121.0.596421684 installed (same version as before but without `-publicbeta` suffix.  Had to force close/reopen it like 10 times but eventually the recording and call screen options showed up.  Recording is working as expected.

Unfortunately, Phone still crashes when I try to change the Call Screen settings for any of the categories.  This was only happening for you on the beta version though?  Are there switches in GAppsMod that could update these settings instead?  I basically want them all to be auto screened.  Also where'd you see the other users having crashes?  Google couldn't find any recent posts about that for me, strangely.  Thx

**Comment by scarlion1** [comment]
Hell yeah, got version 120 installed from APK Mirror and Call Screen works as expected again!

**Comment by scarlion1** [comment]
ugh but now i realized my visual voicemail is completely gone heh, there's no tab for it along the bottom, and no option to even enable it in the Phone's Settings either.  @jacopotediosi are there switches to enable that somewhere? thx
