### ISSUE TITLE
Is there any possibility to make changes in this database without root like by laptop USB debugging ?

### ISSUE THREAD

**Issue by innovatorved** [jacopotediosi/GAppsMod#118]
## Summary
I want to use this feature. But i don't want to root. So, Is there any posibility to make changes in database without root like by laptop USB debugging ?

So i can enable these features.

**Comment by jacopotediosi** [comment]
The crux of this project is to modify the Phenotype database, which resides in Android's private memory, in the path `/data/data`, under the Google Play Services folder. To my knowledge, there is no way to access that path without root.
