### ISSUE TITLE
Google Maps: Eco Mode

### ISSUE THREAD

**Issue by fillwithjoy1** [jacopotediosi/GAppsMod#78]
## Summary
[NOTE]: # ( Provide a brief overview of what the new feature is all about )
Eco Mode that is provided within Google Maps to unsupported countries [link](https://9to5google.com/2022/08/12/google-maps-germany-eco-friendly-routes/)

## Solution
[NOTE]: # ( A clear and concise description of what you want to happen )
A toggle to enable Eco Mode for Google Maps

## Examples
[NOTE]: # ( Show us a picture or mock-up of your proposal )
![image](https://github.com/jacopotediosi/GAppsMod/assets/29514446/5a501e91-4fd5-455d-98a8-4dfd73529fc1)

## Alternatives
[NOTE]: # ( A clear and concise description of any alternative solutions or features you've considered )
None

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )
It's a feature that we don't have!

**Comment by jacopotediosi** [comment]
Please notice that, to my knowledge, Google Maps doesn't use Phenotype DB.
