### ISSUE TITLE
Possible non root solution?

### ISSUE THREAD

**Issue by Roki100** [jacopotediosi/GAppsMod#98]
Would it be by any chance possible to make such mods on non root? maybe patch the apps like revanced or such?

**Comment by jacopotediosi** [comment]
Hi @Roki100 ,
root is required by GAppsMod (you can find some clues about the inner workings [here](https://github.com/jacopotediosi/GAppsMod/issues/88)) and patch the app is out of scope for this project. In my opinion, it would be great if someone could find a way to develop patches for revanced, but I don't know how it works.

**Comment by jacopotediosi** [comment]
Also, please notice that some Google apps are installed as system, so they cannot be replaced without root anyway.
